### ISSUE TITLE
Chinese Titles and Tab labels on german client with "Chinese" option diesab

### ISSUE THREAD

**Issue by Baine** [husandro/WoWTools#12]
**Describe the bug**
frame "collection" has chinese title and tabs labelled in chinese

setting to use chinese is disabled (and as you can see the options are localized):

**To Reproduce**
1. Have German WoW Retail Client
2. Open Collections
3. Look at frame title and tab labels at the bottom

**Expected behavior**
Should remain in German, but are displayed in Chinse

**Screenshots**
![image](https://github.com/husandro/WoWTools/assets/6566469/c762f43a-b8af-4aa2-9130-6ea54090d6b9)
![image](https://github.com/husandro/WoWTools/assets/6566469/011ccb96-5403-4aa6-a611-d261cf2c7ecb)

**Comment by husandro** [comment]
更新一下, 不知解决了吗

**Comment by Baine** [comment]
has been solved indeed. thanks so much <3
